
package com.eidiko.consume.numberconversion;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "NumberConversionSoapType", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NumberConversionSoapType {


    /**
     * Returns the word corresponding to the positive number passed as parameter. Limited to quadrillions.
     * 
     * @param ubiNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NumberToWords")
    @WebResult(name = "NumberToWordsResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "NumberToWords", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.eidiko.consume.numberconversion.NumberToWords")
    @ResponseWrapper(localName = "NumberToWordsResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.eidiko.consume.numberconversion.NumberToWordsResponse")
    public String numberToWords(
        @WebParam(name = "ubiNum", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        BigInteger ubiNum);

    /**
     * Returns the non-zero dollar amount of the passed number.
     * 
     * @param dNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NumberToDollars")
    @WebResult(name = "NumberToDollarsResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "NumberToDollars", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.eidiko.consume.numberconversion.NumberToDollars")
    @ResponseWrapper(localName = "NumberToDollarsResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.eidiko.consume.numberconversion.NumberToDollarsResponse")
    public String numberToDollars(
        @WebParam(name = "dNum", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        BigDecimal dNum);

}
